(() => {
  "use strict";
  const $ = selector => document.querySelector(selector);
  const canvas = $("#terrain");
  const ctx = canvas.getContext("2d", { alpha:false });
  const controls = Object.fromEntries(["water","center","span","gamma","smoothing","contours","liveSensor","rotateProjector","theme"].map(id => [id, $(`#${id}`)]));
  const limitInputs = {center:{min:$("#limitCenterMin"),max:$("#limitCenterMax")},span:{min:$("#limitSpanMin"),max:$("#limitSpanMax")},water:{min:$("#limitWaterMin"),max:$("#limitWaterMax")},smoothing:{min:$("#limitSmoothingMin"),max:$("#limitSmoothingMax")},gamma:{min:$("#limitGammaMin"),max:$("#limitGammaMax")}};
  const defaultRigLimits = {center:{min:1000,max:1500,step:10},span:{min:0,max:300,step:5},water:{min:0,max:65,step:1},smoothing:{min:0,max:92,step:1},gamma:{min:50,max:200,step:1}};
  const grid = { width:640, height:480, values:new Float32Array(640*480) };
  const buffer = document.createElement("canvas"); buffer.width=640; buffer.height=480;
  const bufferCtx = buffer.getContext("2d");
  const image = bufferCtx.createImageData(640,480);
  let frames=0, fpsStarted=performance.now(), dirty=true, liveConnected=false, polling=false, lastDepth=null, apiBase=null, depthFailures=0, calibrating=false, calibrationPoints=[],calibrationDrag=null,calibrationPlane=null,calibrationReferenceField=null,referenceFieldCache=null;
  let calibrationProfile=loadCalibrationProfile();
  migrateLegacyLimits();

  const themes = {
    earth:{name:"Earth",accent:"#b9df62",water:"#0b5790",colors:["#071d43","#136f9b","#d7c17b","#3d853c","#8daa50","#74563a","#c8bda7","#ffffff"]},
    mars:{name:"Mars",accent:"#ff865d",water:"#311a29",colors:["#1d0d0b","#512018","#8c3823","#c85c32","#e58b50","#b97b62","#d3b19b","#f0ddd0"]},
    atlantis:{name:"Atlantis",accent:"#62f2dc",water:"#041e49",colors:["#02091f","#063d67","#087f91","#10bcb2","#6ce2bf","#c0d796","#ead9a3","#fff1d2"]},
    alien:{name:"Alien world",accent:"#d5ff58",water:"#231653",colors:["#090514","#271153","#53218b","#9637a3","#d85a91","#dd9853","#b8e65a","#edffb8"]},
    moon:{name:"Moon",accent:"#e1e1dc",water:"#08090b",colors:["#050506","#202226","#3f4248","#64676b","#8c8e8d","#b3b1aa","#d5d1c7","#faf5e9"]},
    ice:{name:"Glacier",accent:"#c6f5ff",water:"#052a62",colors:["#020817","#07356e","#0877a4","#38b6cf","#8bdae6","#c9edf0","#e8f7f4","#ffffff"]},
    volcanic:{name:"Volcanic",accent:"#ffb33d",water:"#090509",colors:["#020202","#181012","#3f1714","#7c2015","#c23a18","#f27322","#ffc04b","#fff4b0"]},
    desert:{name:"Sahara",accent:"#f2c46d",water:"#174f68",colors:["#302011","#684322","#a76c34","#d99b52","#f0c879","#ead89c","#c29c63","#fff1cc"]},
    forest:{name:"Ancient forest",accent:"#8cda70",water:"#083b42",colors:["#061713","#0c3325","#175936","#2e7941","#58964d","#87a95d","#b7b978","#e2d4a2"]},
    coral:{name:"Coral reef",accent:"#ff8ba0",water:"#04347d",colors:["#031340","#075b9b","#09a8ae","#4cd2b0","#f2c75c","#f37d62","#d84d80","#ffd6b3"]},
    tundra:{name:"Tundra",accent:"#bad8cf",water:"#193d59",colors:["#15282d","#29494a","#526b59","#7c896c","#a7a58b","#c7c4ad","#e0ded1","#ffffff"]},
    synthwave:{name:"Synthwave",accent:"#ff4edb",water:"#080b46",colors:["#05021c","#15106b","#2835b8","#7147d6","#c73dbd","#ff4b85","#ff8956","#ffe071"]},
    thermal:{name:"Thermal",accent:"#ffe66b",water:"#020024",colors:["#000004","#160b39","#4b0c6b","#781c6d","#a52c60","#cf4446","#ed6925","#fb9b06","#f7d13d","#fcffa4"]},
    topographic:{name:"Classic topo",accent:"#e7d06b",water:"#245994",colors:["#123663","#287ba1","#cdbb78","#75934b","#436c38","#765d3f","#a98f6c","#eee5d0"]},
    infrared:{name:"Infrared",accent:"#ff4d6d",water:"#06000c",colors:["#000000","#260044","#67005c","#a80055","#e1303e","#ff7122","#ffc13b","#fff6b7"]},
    copper:{name:"Copper",accent:"#e7a46b",water:"#12100f",colors:["#0d0b0a","#2a1a15","#513026","#794731","#a76643","#cc8b60","#e2b38a","#f2dac0"]},
    emerald:{name:"Emerald city",accent:"#4cf59a",water:"#031a17",colors:["#020b0a","#073227","#075c42","#07865b","#19b775","#5bdb93","#adecad","#efffd1"]},
    candy:{name:"Candy land",accent:"#ff9fdd",water:"#4d3d9a",colors:["#453078","#7258b5","#b36bc1","#ed75ad","#ff9293","#ffb76e","#ffe18a","#fff6cf"]},
    deepsea:{name:"Abyss",accent:"#31d8d0",water:"#01030d",colors:["#000107","#020b24","#061d46","#073c62","#076b78","#169b91","#62c5a8","#caf5d7"]},
    monochrome:{name:"Field study",accent:"#ffffff",water:"#0b0b0b",colors:["#050505","#202020","#3e3e3e","#626262","#898989","#b0b0b0","#d6d6d6","#ffffff"]}
  };
  const hex = value => { const n=parseInt(value.slice(1),16); return [(n>>16)&255,(n>>8)&255,n&255]; };
  Object.values(themes).forEach(theme => { theme.rgb=theme.colors.map(hex); theme.waterRgb=hex(theme.water); });
  Object.entries(themes).forEach(([id,theme]) => controls.theme.add(new Option(theme.name,id)));

  function currentTheme(){ return themes[controls.theme.value] || themes.earth; }
  function resetTerrain(){ for(let y=0;y<480;y++)for(let x=0;x<640;x++){const nx=x/640,ny=y/480;const hill=Math.exp(-((nx-.67)**2+(ny-.42)**2)/.035)*.52;const ridge=Math.exp(-((nx-.27)**2/.02+(ny-.62)**2/.11))*.38;grid.values[y*640+x]=Math.max(0,Math.min(1,.28+hill+ridge+(Math.sin(nx*8.1+Math.cos(ny*6.3))*.5+Math.sin(ny*15.6-nx*3)*.25)*.08));}dirty=true;}
  function samplePalette(value){const colors=currentTheme().rgb;const scaled=Math.max(0,Math.min(.9999,value))*(colors.length-1);const index=Math.floor(scaled),t=scaled-index,a=colors[index],b=colors[Math.min(index+1,colors.length-1)];return [a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t];}
  function pointInPolygon(x,y,points){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if(((a.y>y)!==(b.y>y))&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x)inside=!inside;}return inside;}
  function renderField(){const water=+controls.water.value/100,showContours=controls.contours.checked,waterColor=currentTheme().waterRgb;for(let i=0;i<grid.values.length;i++){const elevation=grid.values[i];let color=elevation<0?[0,0,0]:samplePalette(elevation);if(elevation>=0&&elevation<water){const d=1-elevation/Math.max(.01,water);color=waterColor.map(v=>v*(.72+d*.28));}if(elevation>=water&&showContours){const fraction=(elevation*14)%1,distance=Math.min(fraction,1-fraction),line=Math.max(0,Math.min(1,(.065-distance)/.065));if(line)color=color.map(v=>v*(1-line*.54));}const o=i*4;image.data[o]=color[0];image.data[o+1]=color[1];image.data[o+2]=color[2];image.data[o+3]=255;}bufferCtx.putImageData(image,0,0);dirty=false;}
  function resize(){const rect=canvas.getBoundingClientRect(),scale=Math.min(devicePixelRatio||1,2);if(document.body.classList.contains("projector")){canvas.width=1024;canvas.height=768;}else{canvas.width=Math.round(rect.width*scale);canvas.height=Math.round(rect.height*scale);}}
  function bilinear(points,u,v){const [tl,tr,br,bl]=points;return {x:(1-u)*(1-v)*tl.x+u*(1-v)*tr.x+u*v*br.x+(1-u)*v*bl.x,y:(1-u)*(1-v)*tl.y+u*(1-v)*tr.y+u*v*br.y+(1-u)*v*bl.y};}
  function drawCalibrationGuides(){const points=calibrating?calibrationPoints:null;if(!points?.length)return;const sx=canvas.width/640,sy=canvas.height/480,scaled=points.map(p=>({x:p.x*sx,y:p.y*sy}));ctx.save();ctx.strokeStyle="#d5ff58";ctx.fillStyle="#d5ff58";ctx.lineWidth=Math.max(2,canvas.width/700);ctx.setLineDash([8,6]);if(scaled.length>1){ctx.beginPath();ctx.moveTo(scaled[0].x,scaled[0].y);for(let i=1;i<scaled.length;i++)ctx.lineTo(scaled[i].x,scaled[i].y);if(scaled.length===4)ctx.closePath();ctx.stroke();}for(const [index,p] of scaled.entries()){ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.fill();ctx.fillStyle="#111";ctx.font="bold 11px sans-serif";ctx.textAlign="center";ctx.fillText(String(index+1),p.x,p.y+4);ctx.fillStyle="#d5ff58";}if(scaled.length===4){ctx.setLineDash([4,7]);ctx.globalAlpha=.75;for(let step=1;step<4;step++){const t=step/4,a=bilinear(scaled,t,0),b=bilinear(scaled,t,1),c=bilinear(scaled,0,t),d=bilinear(scaled,1,t);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.moveTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.stroke();}}ctx.restore();}
  function draw(time){if(dirty)renderField();ctx.imageSmoothingEnabled=true;ctx.drawImage(buffer,0,0,canvas.width,canvas.height);drawCalibrationGuides();frames++;if(time-fpsStarted>700){$("#fps").value=`${Math.round(frames*1000/(time-fpsStarted))} fps`;frames=0;fpsStarted=time;}requestAnimationFrame(draw);}
  function depthBounds(){const span=Math.max(1,+controls.span.value),center=+controls.center.value;return {near:Math.max(250,center-span/2),far:Math.min(5000,center+span/2)};}
  function updateReadouts(){const {near,far}=depthBounds();$("#centerValue").value=`${controls.center.value} mm`;$("#spanValue").value=`${controls.span.value} mm`;$("#nearReadout").textContent=`Near ${Math.round(near)} mm`;$("#farReadout").textContent=`Far ${Math.round(far)} mm`;$("#gammaValue").value=`${(+controls.gamma.value/100).toFixed(2)}×`;$("#smoothingValue").value=`${controls.smoothing.value}%`;$("#waterValue").value=`${controls.water.value}%`;}
  function applyTheme(){const theme=currentTheme();document.documentElement.style.setProperty("--accent",theme.accent);$("#themePreview").style.background=`linear-gradient(90deg,${theme.colors.join(",")})`;dirty=true;saveSettings();}
  function saveSettings(){const state={};Object.entries(controls).forEach(([key,input])=>state[key]=input.type==="checkbox"?input.checked:input.value);localStorage.setItem("terrain-lab-settings",JSON.stringify(state));}
  function loadSettings(){try{const state=JSON.parse(localStorage.getItem("terrain-lab-settings"));if(!state)return;Object.entries(state).forEach(([key,value])=>{if(!controls[key])return;if(controls[key].type==="checkbox")controls[key].checked=value;else controls[key].value=value;});}catch(_){}}
  function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
  function normalizeRigLimits(raw={}){const pairs={};for(const [name,fallback] of Object.entries(defaultRigLimits)){let min=Number(raw[name]?.min),max=Number(raw[name]?.max);if(!Number.isFinite(min))min=fallback.min;if(!Number.isFinite(max))max=fallback.max;if(name==="gamma"){min*=raw[name]?.unit==="display"?100:1;max*=raw[name]?.unit==="display"?100:1;}min=clamp(min,name==="center"?250:0,name==="center"?5000:name==="gamma"?400:3000);max=clamp(max,name==="center"?250:0,name==="center"?5000:name==="gamma"?400:3000);if(max<=min)max=Math.min(name==="center"?5000:name==="gamma"?400:3000,min+fallback.step);pairs[name]={min,max,step:fallback.step};}return pairs;}
  function legacyGenericLimits(limits){return limits?.center?.min===500&&limits?.center?.max===3500&&limits?.span?.min===0&&limits?.span?.max===3000;}
  function migrateLegacyLimits(){if(!calibrationProfile||!legacyGenericLimits(calibrationProfile.limits))return;calibrationProfile={...calibrationProfile,limits:normalizeRigLimits({})};localStorage.setItem("terrain-lab-calibration",JSON.stringify(calibrationProfile));}
  function pendingRigLimits(){try{return JSON.parse(localStorage.getItem("terrain-lab-pending-limits")||"null");}catch(_){return null;}}
  function rigLimits(){return normalizeRigLimits(calibrationProfile?.limits||pendingRigLimits()||{});}
  function applyRigLimits(){const limits=rigLimits();for(const [name,limit] of Object.entries(limits)){const input=controls[name];input.min=limit.min;input.max=limit.max;input.step=limit.step;input.value=clamp(Number(input.value)||limit.min,limit.min,limit.max);}return limits;}
  function populateRigLimitInputs(){const limits=rigLimits();for(const [name,limit] of Object.entries(limits)){limitInputs[name].min.value=name==="gamma"?(limit.min/100).toFixed(2):limit.min;limitInputs[name].max.value=name==="gamma"?(limit.max/100).toFixed(2):limit.max;}}
  function readRigLimits(){const raw={};for(const [name,input] of Object.entries(limitInputs)){let min=Number(input.min.value),max=Number(input.max.value);if(name==="gamma"){min*=100;max*=100;}raw[name]={min,max};}return normalizeRigLimits(raw);}
  function persistRigLimits(){const limits=readRigLimits();if(calibrationProfile){calibrationProfile={...calibrationProfile,limits};localStorage.setItem("terrain-lab-calibration",JSON.stringify(calibrationProfile));}else localStorage.setItem("terrain-lab-pending-limits",JSON.stringify(limits));applyRigLimits();updateReadouts();dirty=true;}
  function projectorOffset(){const offset=calibrationProfile?.projectorOffset||{};return {x:clamp(Number(offset.x)||0,-500,500),y:clamp(Number(offset.y)||0,-500,500)};}
  function updateAlignmentReadout(){const offset=projectorOffset(),readout=$("#alignmentReadout");if(readout)readout.value=`${offset.x} px, ${offset.y} px`;}
  function applyProjectionOrientation(){document.body.classList.toggle("flip-180",!!controls.rotateProjector.checked);const offset=projectorOffset(),translation=document.body.classList.contains("projector")?`translate(${offset.x}px, ${offset.y}px) `:"";canvas.style.transform=`${translation}rotate(${controls.rotateProjector.checked?180:0}deg)`;updateAlignmentReadout();}
  function refreshSharedState(){loadSettings();calibrationProfile=loadCalibrationProfile();migrateLegacyLimits();referenceFieldCache=null;applyRigLimits();updateReadouts();applyProjectionOrientation();const theme=currentTheme();document.documentElement.style.setProperty("--accent",theme.accent);$("#themePreview").style.background=`linear-gradient(90deg,${theme.colors.join(",")})`;updateCalibrationStatus();dirty=true;}
  function loadCalibrationProfile(){try{const profile=JSON.parse(localStorage.getItem("terrain-lab-calibration"));return profile?.version>=1&&profile.roi?.length===4?profile:null;}catch(_){return null;}}
  function updateCalibrationStatus(){$("#calibrationStatus").textContent=calibrationProfile?"Calibration ✓":"Calibrate";$("#startCalibration").classList.toggle("ready",!!calibrationProfile);}
  function updateFlatReferenceStatus(){const status=$("#flatReferenceStatus"),plane=calibrationPlane||calibrationProfile?.referencePlane,field=calibrationReferenceField||calibrationProfile?.referenceField;if(!plane&&!field){status.textContent="Place a flat lid over the inner box, then capture its level.";status.classList.remove("ready");return;}status.textContent=field?"Flat reference captured · full-box level correction active":`Flat reference captured · tilt correction ${Math.round(plane.rmsMm||0)} mm residual`;status.classList.add("ready");}
  function updateCalibrationPrompt(){const names=["top-left","top-right","bottom-right","bottom-left"];$("#calibrationCount").textContent=`${calibrationPoints.length} / 4`;$("#calibrationInstruction").textContent=calibrationPoints.length<4?`Select ${names[calibrationPoints.length]} corner`:"Drag corners to resize, or drag inside to move";$("#undoCalibration").disabled=!calibrationPoints.length;$("#saveCalibration").disabled=calibrationPoints.length!==4;$("#captureFlatReference").disabled=calibrationPoints.length!==4||!lastDepth;updateFlatReferenceStatus();}
  function startCalibration(){calibrating=true;calibrationPoints=calibrationProfile?.roi?.map(point=>({...point}))||[];calibrationPlane=calibrationProfile?.referencePlane||null;calibrationReferenceField=calibrationProfile?.referenceField||null;calibrationDrag=null;$("#calibrationPrompt").hidden=false;$("#controlsPanel").classList.add("collapsed");$("#rotateProjection").textContent=controls.rotateProjector.checked?"↻ Projection rotated":"↻ Rotate projection";populateRigLimitInputs();updateAlignmentReadout();canvas.style.cursor="crosshair";updateCalibrationPrompt();}
  function cancelCalibration(){calibrating=false;calibrationPoints=[];calibrationPlane=null;calibrationReferenceField=null;calibrationDrag=null;$("#calibrationPrompt").hidden=true;$("#controlsPanel").classList.remove("collapsed");canvas.style.cursor="default";}
  function captureCalibrationCorner(event){if(!calibrating||calibrationPoints.length===4)return;const rect=canvas.getBoundingClientRect();calibrationPoints.push({x:Math.round((event.clientX-rect.left)/rect.width*640),y:Math.round((event.clientY-rect.top)/rect.height*480)});updateCalibrationPrompt();}
  function calibrationPointer(event){const rect=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(639,(event.clientX-rect.left)/rect.width*640)),y:Math.max(0,Math.min(479,(event.clientY-rect.top)/rect.height*480)),hitRadius:18*640/rect.width};}
  function startCalibrationDrag(event){if(!calibrating||calibrationPoints.length!==4)return;const point=calibrationPointer(event),hit=calibrationPoints.findIndex(corner=>Math.hypot(corner.x-point.x,corner.y-point.y)<point.hitRadius);if(hit>=0)calibrationDrag={type:"corner",index:hit};else if(pointInPolygon(point.x,point.y,calibrationPoints))calibrationDrag={type:"move",point,original:calibrationPoints.map(corner=>({...corner}))};else return;canvas.setPointerCapture?.(event.pointerId);canvas.style.cursor="grabbing";event.preventDefault();}
  function moveCalibrationDrag(event){if(!calibrationDrag)return;const point=calibrationPointer(event);if(calibrationDrag.type==="corner"){calibrationPoints[calibrationDrag.index]={x:Math.round(point.x),y:Math.round(point.y)};}else{const rawX=point.x-calibrationDrag.point.x,rawY=point.y-calibrationDrag.point.y,minX=Math.min(...calibrationDrag.original.map(corner=>corner.x)),maxX=Math.max(...calibrationDrag.original.map(corner=>corner.x)),minY=Math.min(...calibrationDrag.original.map(corner=>corner.y)),maxY=Math.max(...calibrationDrag.original.map(corner=>corner.y)),dx=Math.max(-minX,Math.min(639-maxX,rawX)),dy=Math.max(-minY,Math.min(479-maxY,rawY));calibrationPoints=calibrationDrag.original.map(corner=>({x:Math.round(corner.x+dx),y:Math.round(corner.y+dy)}));}dirty=true;event.preventDefault();}
  function stopCalibrationDrag(event){if(!calibrationDrag)return;calibrationDrag=null;canvas.releasePointerCapture?.(event.pointerId);canvas.style.cursor="crosshair";event.preventDefault();}
  function detectCalibrationCorners(){if(!lastDepth){$("#calibrationInstruction").textContent="Connect Kinect, then try again";return;}const samples=[];for(let y=48;y<384;y+=4)for(let x=80;x<560;x+=4){const depth=lastDepth[y*640+x];if(depth>250&&depth<5000)samples.push(depth);}if(samples.length<100){$("#calibrationInstruction").textContent="No usable depth surface found";return;}samples.sort((a,b)=>a-b);const level=samples[Math.floor(samples.length/2)],tolerance=80,inside=depth=>Math.abs(depth-level)<=tolerance;let seed=-1,best=Infinity;for(let y=48;y<384;y+=3)for(let x=80;x<560;x+=3){const index=y*640+x,depth=lastDepth[index],distance=(x-320)**2+(y-220)**2;if(inside(depth)&&distance<best){seed=index;best=distance;}}if(seed<0){$("#calibrationInstruction").textContent="No flat sand surface found";return;}const seen=new Uint8Array(640*480),stack=[seed];seen[seed]=1;let count=0,minX=640,maxX=0,minY=480,maxY=0;while(stack.length){const index=stack.pop(),depth=lastDepth[index];if(!inside(depth))continue;const x=index%640,y=(index/640)|0;count++;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);for(const next of [index-1,index+1,index-640,index+640])if(next>=0&&next<seen.length&&!seen[next]){seen[next]=1;stack.push(next);}}const width=maxX-minX+1,height=maxY-minY+1,fill=count/(width*height);if(count<12000||width<120||height<90||fill<.45||minX<12||maxX>627||minY<12||maxY>467){$("#calibrationInstruction").textContent="No complete inner sand rectangle found";return;}const inset=3;calibrationPoints=[{x:minX+inset,y:minY+inset},{x:maxX-inset,y:minY+inset},{x:maxX-inset,y:maxY-inset},{x:minX+inset,y:maxY-inset}];updateCalibrationPrompt();$("#calibrationInstruction").textContent="Inner sand area detected — review, then Save";}
  function toggleProjectorRotation(){controls.rotateProjector.checked=!controls.rotateProjector.checked;applyProjectionOrientation();saveSettings();$("#rotateProjection").textContent=controls.rotateProjector.checked?"↻ Projection rotated":"↻ Rotate projection";}
  function nudgeProjection(dx,dy){if(!calibrationProfile){$("#calibrationInstruction").textContent="Save the sandbox box before alignment";return;}const offset=projectorOffset();calibrationProfile={...calibrationProfile,projectorOffset:{x:offset.x+dx,y:offset.y+dy}};localStorage.setItem("terrain-lab-calibration",JSON.stringify(calibrationProfile));applyProjectionOrientation();dirty=true;}
  function resetProjectionAlignment(){if(!calibrationProfile)return;calibrationProfile={...calibrationProfile,projectorOffset:{x:0,y:0}};localStorage.setItem("terrain-lab-calibration",JSON.stringify(calibrationProfile));applyProjectionOrientation();dirty=true;}
  function encodeReferenceField(values){const bytes=new Uint8Array(values.buffer),chunks=[];for(let i=0;i<bytes.length;i+=4096)chunks.push(String.fromCharCode(...bytes.subarray(i,i+4096)));return btoa(chunks.join(""));}
  function decodeReferenceField(field){if(!field?.data||field.width<2||field.height<2)return null;try{const binary=atob(field.data),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes.byteLength===field.width*field.height*2?new Uint16Array(bytes.buffer):null;}catch(_){return null;}}
  function captureFlatReference(){if(!lastDepth||calibrationPoints.length!==4){$("#flatReferenceStatus").textContent="Connect Kinect and finish the inner-box outline first.";return;}const width=80,height=60,values=new Uint16Array(width*height);let total=0,count=0;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const point=bilinear(calibrationPoints,x/(width-1),y/(height-1)),depth=Math.round(sampleDepthBilinear(point.x,point.y));if(depth<250||depth>5000){$("#flatReferenceStatus").textContent="The lid is not visible across the entire box. Check the Kinect view.";return;}values[y*width+x]=depth;total+=depth;count++;}calibrationReferenceField={width,height,data:encodeReferenceField(values),baseline:Math.round(total/count),capturedAt:new Date().toISOString()};referenceFieldCache={data:calibrationReferenceField.data,values};calibrationPlane=null;$("#flatReferenceStatus").textContent="Flat reference captured · full-box level correction active";$("#flatReferenceStatus").classList.add("ready");dirty=true;}
  function saveCalibration(){if(calibrationPoints.length!==4)return;calibrationProfile={version:4,name:"Default rig",createdAt:new Date().toISOString(),sensor:{width:640,height:480},roi:calibrationPoints.map(p=>({...p})),referencePlane:calibrationPlane||null,referenceField:calibrationReferenceField||null,limits:readRigLimits(),projectorOffset:projectorOffset()};referenceFieldCache=null;localStorage.setItem("terrain-lab-calibration",JSON.stringify(calibrationProfile));localStorage.removeItem("terrain-lab-pending-limits");applyRigLimits();updateReadouts();updateCalibrationStatus();dirty=true;cancelCalibration();}
  function resetCalibrationProfile(){localStorage.removeItem("terrain-lab-calibration");calibrationProfile=null;applyRigLimits();updateReadouts();updateCalibrationStatus();dirty=true;cancelCalibration();}
  function exportConfiguration(){const settings=JSON.parse(localStorage.getItem("terrain-lab-settings")||"{}"),calibration=JSON.parse(localStorage.getItem("terrain-lab-calibration")||"null");if(!calibration){$("#flatReferenceStatus").textContent="Save a rig calibration before downloading a backup.";return;}const backup={format:"terrain-lab-rig",version:1,exportedAt:new Date().toISOString(),settings,calibration},blob=new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="terrain-lab-rig-config.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),500);$("#flatReferenceStatus").textContent="Rig configuration downloaded.";}
  async function restoreConfiguration(event){const file=event.target.files?.[0];event.target.value="";if(!file)return;try{const backup=JSON.parse(await file.text());if(backup?.format!=="terrain-lab-rig"||!backup.calibration?.roi||backup.calibration.roi.length!==4)throw new Error("invalid");localStorage.setItem("terrain-lab-settings",JSON.stringify(backup.settings||{}));localStorage.setItem("terrain-lab-calibration",JSON.stringify(backup.calibration));refreshSharedState();calibrationPoints=calibrationProfile.roi.map(point=>({...point}));calibrationPlane=calibrationProfile.referencePlane||null;calibrationReferenceField=calibrationProfile.referenceField||null;updateCalibrationPrompt();$("#flatReferenceStatus").textContent="Rig configuration restored. Review the outline, then Save rig.";$("#flatReferenceStatus").classList.add("ready");}catch(_){$("#flatReferenceStatus").textContent="That file is not a Terrain Lab rig configuration.";}}
  function planeDepth(plane,x,y){if(!plane)return NaN;const inverse=plane.a*(x-320)/320+plane.b*(y-240)/240+plane.c;return inverse>0?1/inverse:NaN;}
  function referenceDepth(field,u,v){if(!field)return NaN;if(!referenceFieldCache||referenceFieldCache.data!==field.data){const values=decodeReferenceField(field);if(!values)return NaN;referenceFieldCache={data:field.data,values};}const x=clamp(u,0,1)*(field.width-1),y=clamp(v,0,1)*(field.height-1),x0=Math.floor(x),y0=Math.floor(y),x1=Math.min(field.width-1,x0+1),y1=Math.min(field.height-1,y0+1),tx=x-x0,ty=y-y0,values=referenceFieldCache.values,a=values[y0*field.width+x0],b=values[y0*field.width+x1],c=values[y1*field.width+x0],d=values[y1*field.width+x1];return a*(1-tx)*(1-ty)+b*tx*(1-ty)+c*(1-tx)*ty+d*tx*ty;}
  function compensatedDepth(depth,x,y,u=x/639,v=y/479){const field=calibrating?calibrationReferenceField:(calibrationProfile?.referenceField||null),fieldExpected=referenceDepth(field,u,v);if(field&&Number.isFinite(fieldExpected)&&Number.isFinite(field.baseline))return depth-fieldExpected+field.baseline;const plane=calibrating?calibrationPlane:(calibrationProfile?.referencePlane||null),expected=planeDepth(plane,x,y),baseline=plane?.baseline;if(!plane||!Number.isFinite(expected)||!Number.isFinite(baseline))return depth;return depth-expected+baseline;}
  function autoFit(){if(!lastDepth)return;const roi=calibrationProfile?.roi,valid=[],limits=rigLimits();if(roi){for(let y=0;y<480;y+=3)for(let x=0;x<640;x+=3){const point=bilinear(roi,x/639,y/479),sx=Math.max(0,Math.min(639,Math.round(point.x))),sy=Math.max(0,Math.min(479,Math.round(point.y))),depth=compensatedDepth(lastDepth[sy*640+sx],sx,sy,x/639,y/479);if(depth>250&&depth<5000)valid.push(depth);}}else for(let y=0;y<480;y+=3)for(let x=0;x<640;x+=3){const depth=compensatedDepth(lastDepth[y*640+x],x,y,x/639,y/479);if(depth>250&&depth<5000)valid.push(depth);}valid.sort((a,b)=>a-b);if(valid.length<100)return;const low=valid[Math.floor(valid.length*.03)],high=valid[Math.floor(valid.length*.97)],span=clamp(Math.round((high-low)*1.25/limits.span.step)*limits.span.step,limits.span.min,limits.span.max),center=clamp(Math.round((low+high)/20)*10,limits.center.min,limits.center.max);controls.center.value=center;controls.span.value=span;updateReadouts();saveSettings();dirty=true;}
  function setSensorStatus(connected,message){liveConnected=connected;$("#statusText").textContent=message;$("#statusDot").classList.toggle("offline",!connected);$("#projector").disabled=!connected;$("#connectKinect").classList.toggle("connected",connected);$("#connectKinect").textContent=connected?"Disconnect":"Connect Kinect";}
  async function localFetch(url,options={}){return fetch(url,{cache:"no-store",mode:"cors",targetAddressSpace:"loopback",...options});}
  async function probe(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),1200);try{const response=await localFetch(`${url}/api/status?t=${Date.now()}`,{signal:controller.signal});if(!response.ok)return null;return await response.json();}catch(_){return null;}finally{clearTimeout(timer);}}
  async function bridgeCommand(base,path){try{const response=await localFetch(`${base}${path}`,{method:"POST"});return response.ok;}catch(_){return false;}}
  async function waitForFrame(base){for(let attempt=0;attempt<24;attempt++){const status=await probe(base);if(status?.connected)return true;await new Promise(resolve=>setTimeout(resolve,250));}return false;}
  async function connectKinect(){if(apiBase){await bridgeCommand(apiBase,"/api/disconnect");apiBase=null;depthFailures=0;setSensorStatus(false,"Not connected");resetTerrain();return;}const button=$("#connectKinect");button.disabled=true;button.textContent="Searching…";$("#statusText").textContent="Looking for local bridge";const bases=[];if(location.protocol==="http:"&&/^(localhost|127\.0\.0\.1)$/.test(location.hostname))bases.push(location.origin);for(let port=8080;port<=8099;port++)bases.push(`http://127.0.0.1:${port}`);let bridgeSeen=false;for(const base of [...new Set(bases)]){const status=await probe(base);if(!status)continue;bridgeSeen=true;apiBase=base;await bridgeCommand(base,"/api/connect");if(await waitForFrame(base)){depthFailures=0;setSensorStatus(true,"Kinect live");break;}setSensorStatus(false,"Kinect starting");break;}button.disabled=false;if(!apiBase)setSensorStatus(false,bridgeSeen?"Kinect unavailable":"Start the local bridge");}
  function sampleDepthBilinear(x,y){const x0=Math.max(0,Math.min(639,Math.floor(x))),y0=Math.max(0,Math.min(479,Math.floor(y))),x1=Math.min(639,x0+1),y1=Math.min(479,y0+1),tx=x-x0,ty=y-y0,a=lastDepth[y0*640+x0],b=lastDepth[y0*640+x1],c=lastDepth[y1*640+x0],d=lastDepth[y1*640+x1];if(a&&b&&c&&d)return a*(1-tx)*(1-ty)+b*tx*(1-ty)+c*(1-tx)*ty+d*tx*ty;return lastDepth[Math.max(0,Math.min(639,Math.round(x)))+Math.max(0,Math.min(479,Math.round(y)))*640];}
  function updateDepthGrid(){const {near,far}=depthBounds(),gamma=+controls.gamma.value/100,keep=+controls.smoothing.value/100,mix=1-keep,roi=calibrationProfile?.roi,[tl,tr,br,bl]=roi||[];for(let y=0;y<480;y++)for(let x=0;x<640;x++){let sx=x,sy=y;if(roi){const u=x/639,v=y/479,topX=tl.x+(tr.x-tl.x)*u,topY=tl.y+(tr.y-tl.y)*u,bottomX=bl.x+(br.x-bl.x)*u,bottomY=bl.y+(br.y-bl.y)*u;sx=topX+(bottomX-topX)*v;sy=topY+(bottomY-topY)*v;}const i=y*640+x,depth=compensatedDepth(sampleDepthBilinear(sx,sy),sx,sy,x/639,y/479);if(depth>0&&depth<=far+200){let elevation=Math.max(0,Math.min(1,(far-depth)/(far-near)));elevation=Math.pow(elevation,1/gamma);grid.values[i]=liveConnected&&grid.values[i]>=0?grid.values[i]*keep+elevation*mix:elevation;}else grid.values[i]=-1;}}
  async function pollDepth(){if(polling||!apiBase)return;polling=true;try{if(!controls.liveSensor.checked){setSensorStatus(false,"Live depth paused");return;}const response=await localFetch(`${apiBase}/api/depth?t=${Date.now()}`);if(response.status===503){setSensorStatus(false,"Kinect starting");await new Promise(resolve=>setTimeout(resolve,500));return;}if(!response.ok)throw new Error("No depth frame");lastDepth=new Uint16Array(await response.arrayBuffer());if(calibrating)updateCalibrationPrompt();updateDepthGrid();depthFailures=0;setSensorStatus(true,"Kinect live");dirty=true;}catch(_){if(++depthFailures>5){apiBase=null;setSensorStatus(false,"Connection lost");}}finally{polling=false;}}
  function openProjectorWindow(){const url=new URL(location.href);url.searchParams.set("projection","1");url.searchParams.set("autoconnect","1");if(controls.rotateProjector.checked)url.searchParams.set("rotate","180");else url.searchParams.delete("rotate");const child=window.open(url.toString(),"terrain-lab-projector","popup=yes,width=1024,height=768");if(!child)$("#statusText").textContent="Allow pop-ups to open projector";}
  Object.entries(controls).forEach(([name,input])=>input.addEventListener("input",()=>{updateReadouts();applyProjectionOrientation();if(name==="theme")applyTheme();else{dirty=true;saveSettings();}}));
  canvas.addEventListener("click",captureCalibrationCorner);canvas.addEventListener("pointerdown",startCalibrationDrag);canvas.addEventListener("pointermove",moveCalibrationDrag);canvas.addEventListener("pointerup",stopCalibrationDrag);canvas.addEventListener("pointercancel",stopCalibrationDrag);$("#startCalibration").addEventListener("click",startCalibration);$("#autoCalibration").addEventListener("click",detectCalibrationCorners);$("#captureFlatReference").addEventListener("click",captureFlatReference);$("#rotateProjection").addEventListener("click",toggleProjectorRotation);$("#resetCalibration").addEventListener("click",resetCalibrationProfile);$("#cancelCalibration").addEventListener("click",cancelCalibration);$("#undoCalibration").addEventListener("click",()=>{calibrationPoints.pop();updateCalibrationPrompt();});$("#saveCalibration").addEventListener("click",saveCalibration);Object.values(limitInputs).forEach(pair=>Object.values(pair).forEach(input=>input.addEventListener("change",persistRigLimits)));$("#exportConfig").addEventListener("click",exportConfiguration);$("#importConfig").addEventListener("click",()=>$("#configFile").click());$("#configFile").addEventListener("change",restoreConfiguration);$("#connectKinect").addEventListener("click",connectKinect);$("#autoRange").addEventListener("click",autoFit);$("#collapseControls").addEventListener("click",()=>$("#controlsPanel").classList.add("collapsed"));$("#showControls").addEventListener("click",()=>$("#controlsPanel").classList.remove("collapsed"));
  document.querySelectorAll("[data-nudge]").forEach(button=>button.addEventListener("click",()=>{const step=6,direction=button.dataset.nudge;nudgeProjection(direction==="left"?-step:direction==="right"?step:0,direction==="up"?-step:direction==="down"?step:0);}));$("#resetAlignment").addEventListener("click",resetProjectionAlignment);
  $("#projector").addEventListener("click",openProjectorWindow);document.addEventListener("keydown",e=>{const projection=new URLSearchParams(location.search).has("projection");if(e.key.toLowerCase()==="f"&&!projection)openProjectorWindow();if(e.key.toLowerCase()==="f"&&projection)document.documentElement.requestFullscreen?.().catch(()=>{});if(e.key.toLowerCase()==="r"&&projection){controls.rotateProjector.checked=!controls.rotateProjector.checked;applyProjectionOrientation();saveSettings();}});window.addEventListener("resize",resize);window.addEventListener("storage",event=>{if(event.key==="terrain-lab-settings"||event.key==="terrain-lab-calibration")refreshSharedState();});
  const params=new URLSearchParams(location.search),projectionMode=params.has("projection");loadSettings();if(params.get("rotate")==="180")controls.rotateProjector.checked=true;if(!controls.theme.value)controls.theme.value="earth";applyRigLimits();updateReadouts();updateCalibrationStatus();applyTheme();resetTerrain();if(projectionMode){document.body.classList.add("projector");$("#controlsPanel").hidden=true;$("#showControls").hidden=true;}applyProjectionOrientation();resize();setSensorStatus(false,"Not connected");setInterval(pollDepth,33);if(params.has("autoconnect"))setTimeout(connectKinect,300);requestAnimationFrame(draw);
})();
