export const dashboardHtml = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Terrain Lab · Private analytics</title><link rel="stylesheet" href="/dashboard.css"><script src="/dashboard.js" defer></script></head>
<body><header><a href="https://msriram.github.io/terrain-lab/">≋ TERRAIN LAB</a><span>PRIVATE FIELD NOTES</span><form method="post" action="/logout"><button>Sign out</button></form></header>
<main><div class="intro"><div><p class="eyebrow">OWNER ANALYTICS</p><h1>How the worlds are used.</h1><p>Anonymous, aggregate activity only. No depth frames or visitor identities are collected.</p></div><label>Period <select id="days"><option value="7">Last 7 days</option><option value="30" selected>Last 30 days</option><option value="90">Last 90 days</option></select></label></div>
<p id="message" role="status">Loading…</p><section id="summary" class="cards" aria-label="Summary"></section>
<div class="grid"><section><h2>Daily activity</h2><div id="daily" class="bars"></div></section><section><h2>Popular worlds</h2><div id="worlds"></div></section><section><h2>Modes</h2><div id="modes"></div></section><section><h2>Interactions</h2><div id="interactions"></div></section><section><h2>Kinect &amp; projector</h2><div id="hardware"></div></section><section><h2>Experience quality</h2><div id="quality"></div></section></div>
<p class="foot">Counts are events, not unique people. Collection begins only after this backend is configured and deployed.</p></main></body></html>`;

export const dashboardCss = `:root{font-family:ui-sans-serif,system-ui,sans-serif;color:#e0eade;background:#0b181b}*{box-sizing:border-box}body{margin:0}header{display:flex;align-items:center;gap:18px;border-bottom:1px solid #294043;padding:17px clamp(20px,4vw,65px);font-size:11px;letter-spacing:.13em}header a{color:#e0eade;text-decoration:none;font-weight:700}header span{color:#7fa39f}header form{margin-left:auto}button,select{background:#1a3031;color:#d8e9db;border:1px solid #42605b;border-radius:3px;padding:8px 12px;cursor:pointer}main{max-width:1330px;margin:auto;padding:45px clamp(20px,4vw,65px)}.intro{display:flex;justify-content:space-between;align-items:end;gap:18px}.eyebrow{font-size:10px;letter-spacing:.18em;color:#b9d990}h1{font:normal clamp(32px,4vw,54px) Georgia,serif;margin:8px 0 13px}h2{font:normal 23px Georgia,serif;margin:0 0 20px}.intro p:not(.eyebrow),.foot,#message{color:#9bb1aa;font-size:13px;line-height:1.5}.intro label{display:flex;align-items:center;gap:10px;white-space:nowrap;font-size:12px}.cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:13px;margin:32px 0}.card,.grid section{border:1px solid #294043;background:#112429;border-radius:5px;padding:22px}.card strong{display:block;font:normal 36px Georgia,serif;color:#d5edaf}.card span{display:block;color:#91aca5;font-size:11px;letter-spacing:.06em;margin-top:10px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.row{display:grid;grid-template-columns:minmax(105px,1fr) 2fr 48px;gap:10px;align-items:center;margin:12px 0;font-size:12px;color:#d6e5df}.row span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.bar{height:9px;border-radius:10px;background:#294341;overflow:hidden}.bar i{display:block;background:#b7d995;height:100%;border-radius:10px}.row b{text-align:right;font-weight:500}.day{display:grid;grid-template-columns:85px 1fr 45px;gap:10px;align-items:center;margin:9px 0;font-size:11px;color:#a5bbb4}.empty{color:#78928a;font-size:12px}.foot{padding:25px 0}@media(max-width:800px){.cards,.grid{grid-template-columns:1fr 1fr}.intro{align-items:start;flex-direction:column}}@media(max-width:560px){.cards,.grid{grid-template-columns:1fr}header span{display:none}}`;

export const dashboardJs = `const $=id=>document.getElementById(id);
const number=value=>new Intl.NumberFormat().format(value||0);
const title=value=>value.replaceAll('_',' ').replace(/\\b\\w/g,c=>c.toUpperCase());
function rows(id,items){const el=$(id);el.replaceChildren();if(!items.length){el.textContent='No events yet.';el.className='empty';return;}el.className='';const peak=Math.max(1,...items.map(x=>x.total));for(const item of items.slice(0,12)){const row=document.createElement('div');row.className='row';const label=document.createElement('span');label.textContent=title(item.label);const bar=document.createElement('div');bar.className='bar';const fill=document.createElement('i');fill.style.width=(item.total/peak*100)+'%';bar.append(fill);const count=document.createElement('b');count.textContent=number(item.total);row.append(label,bar,count);el.append(row);}}
async function load(){const days=$('days').value;$('message').textContent='Loading…';try{const response=await fetch('/api/report?days='+days,{credentials:'same-origin'});if(response.status===401){location.href='/login';return;}if(!response.ok)throw Error('Report unavailable');const data=await response.json();const total=(event)=>data.events.filter(x=>x.event===event).reduce((n,x)=>n+x.total,0);const cards=[['Page views',total('page_view')],['World changes',total('world_change')],['Wildlife rescues',total('rescue')],['Kinect connects',total('kinect_connected')]];$('summary').replaceChildren(...cards.map(([name,value])=>{const card=document.createElement('div');card.className='card';const strong=document.createElement('strong');strong.textContent=number(value);const span=document.createElement('span');span.textContent=name;card.append(strong,span);return card;}));const group=(filter,key)=>Object.values(data.events.filter(filter).reduce((map,item)=>{const label=key(item);(map[label]??={label,total:0}).total+=item.total;return map;},{})).sort((a,b)=>b.total-a.total);rows('worlds',group(x=>x.event==='world_change'||x.event==='page_view',x=>x.theme).filter(x=>x.label!=='none'));rows('modes',group(x=>x.event==='page_view',x=>x.mode));rows('interactions',group(x=>['rescue','capture','arrest','terrain_edit','population_change','landscape_randomize'].includes(x.event),x=>x.event));rows('hardware',group(x=>['kinect_connected','kinect_failed','kinect_disconnected','projector_opened','calibration_saved'].includes(x.event),x=>x.event));rows('quality',group(x=>['fps','session_length'].includes(x.event),x=>x.event+': '+x.detail));const daily=$('daily');daily.replaceChildren();const values=data.daily||[];const peak=Math.max(1,...values.map(x=>x.total));for(const item of values){const row=document.createElement('div');row.className='day';const date=document.createElement('span');date.textContent=item.day;const bar=document.createElement('div');bar.className='bar';const fill=document.createElement('i');fill.style.width=(item.total/peak*100)+'%';bar.append(fill);const count=document.createElement('b');count.textContent=number(item.total);row.append(date,bar,count);daily.append(row);}if(!values.length)daily.textContent='No events yet.';$('message').textContent='Updated '+new Date().toLocaleString();}catch(error){$('message').textContent=error.message;}}
$('days').addEventListener('change',load);load();`;
