import { WORLD_FAUNA } from "./world-fauna.js";
// Scenery recipes share terrain rules; each theme has its own palette and motion.
export const LANDSCAPES = {
  earth: {
    label: "Earth",
    props: ["tree", "tree", "flowers", "rock"],
    colors: ["#4e8050", "#8caf67", "#d3a969"],
    weather: "clouds",
    waves: true,
    caption: "Wind in the trees. Waves finding the shore.",
  },
  mars: {
    label: "Mars",
    props: ["rock", "spire", "rock"],
    colors: ["#a95437", "#d88754", "#754032"],
    weather: "dust",
    caption: "Rust-red spires and wandering dust devils.",
  },
  atlantis: {
    label: "Atlantis",
    props: ["castle", "drownedtower", "brokenarch", "ruin", "seaweed", "seaweed", "seaweed", "chest", "trident", "coral"],
    colors: ["#345b64", "#456f73", "#577972"],
    weather: "bubbles",
    underwater: true,
    caption: "Broken castles and moss-covered towers fade into blue water; merpeople patrol the lost kingdom.",
  },
  alien: {
    label: "Alien world",
    props: ["mushroom", "crystal", "mushroom"],
    colors: ["#b46bc8", "#79ebbd", "#f4ba71"],
    weather: "spores",
    caption: "Breathing mushrooms and drifting luminous spores.",
  },
  moon: {
    label: "Moon",
    props: ["crater", "antenna"],
    colors: ["#98a4ad", "#d0d7d7", "#596677"],
    weather: "meteors",
    caption: "Silent craters under a passing meteor shower.",
  },
  ice: {
    label: "Glacier",
    props: ["crystal", "snowpine", "rock"],
    colors: ["#a0dceb", "#edf9ef", "#73aeca"],
    weather: "snow",
    waves: true,
    caption: "Narwhals beneath the ice; bears, penguins, and walruses along the floes.",
  },
  volcanic: {
    label: "Volcanic",
    props: ["rock", "spire", "rock"],
    colors: ["#413c45", "#963c31", "#ff7934"],
    weather: "embers",
    eruption: true,
    caption: "Raise a tall mountain to awaken the volcano.",
  },
  desert: {
    label: "Sahara",
    props: ["palm", "cactus", "rock"],
    colors: ["#859453", "#d9b878", "#af8553"],
    weather: "sand",
    waves: true,
    caption: "Windblown dunes and palms beside the oasis.",
  },
  forest: {
    label: "Ancient forest",
    props: ["forestgrove", "forestgrove", "forestgrove", "mushroom"],
    colors: ["#123d30", "#1f533c", "#345b38"],
    weather: "rain",
    waves: true,
    caption: "Dark, layered rainforest canopy beneath rainclouds and circling black birds.",
  },
  coral: {
    label: "Coral reef",
    props: ["seaweed", "shell"],
    colors: ["#ee947d", "#6bcbb2", "#dac188"],
    weather: "bubbles",
    underwater: true,
    caption: "Small translucent coral colonies gather in living clusters wherever sand rises.",
  },
  tundra: {
    label: "Tundra",
    props: ["meadow", "coniferstand", "rockpeak"],
    colors: ["#6d7541", "#a3a05a", "#d8d7c9"],
    weather: "snow",
    waves: true,
    caption: "Gold-green tundra gives way to conifer stands, bare rock, and snow above the treeline.",
  },
  synthwave: {
    label: "Synthwave",
    props: ["pyramid", "crystal", "arch"],
    colors: ["#e67dca", "#75ceda", "#9975d9"],
    weather: "neon",
    caption: "Neon beasts and strange spirits spring beneath a synthetic sunset.",
  },
  thermal: {
    label: "Thermal",
    props: ["vent", "crystal", "rock"],
    colors: ["#dd925e", "#e3c374", "#ab5d78"],
    weather: "steam",
    caption: "Geothermal pools release slow columns of steam.",
  },
  topographic: {
    label: "Classic topo",
    props: ["tree", "marker", "rock"],
    colors: ["#638052", "#d8c087", "#a08a66"],
    weather: "clouds",
    waves: true,
    caption: "Survey markers, pine groves, and a coastal breeze.",
  },
  infrared: {
    label: "Infrared",
    props: ["crystal", "spire", "vent"],
    colors: ["#df6475", "#ffa16b", "#85549d"],
    weather: "embers",
    caption: "Warm fissures and drifting embers reveal the land.",
  },
  copper: {
    label: "Copper",
    props: ["gear", "spire", "pipe"],
    colors: ["#ba8968", "#7bb5a5", "#e0bb82"],
    weather: "steam",
    caption: "Copper mechanisms and patina-tinted steam.",
  },
  emerald: {
    label: "Emerald city",
    props: ["tower", "crystal", "arch"],
    colors: ["#58b88d", "#b0df95", "#dfc68b"],
    weather: "fireflies",
    caption: "Jade towers glow beneath a cloud of fireflies.",
  },
  candy: {
    label: "Candy land",
    props: ["lollipop", "gumdrop", "mushroom"],
    colors: ["#e986b2", "#f3ce80", "#a3c8dc"],
    weather: "sprinkles",
    clouds: true,
    caption: "Cotton-candy clouds and falling rainbow sprinkles.",
  },
  deepsea: {
    label: "Talokan",
    props: ["talokan-temple", "talokan-district", "talokan-district", "talokan-district", "talokan-beacon", "talokan-beacon", "seaweed", "vent"],
    colors: ["#142b30", "#28505a", "#4b7775"],
    weather: "marine-snow",
    underwater: true,
    caption: "A hidden deep-water city glows beneath the marine snow.",
  },
  universe: {
    label: "Universe",
    props: ["nebula", "starfield", "dustlane"],
    colors: ["#7050b7", "#ffbf8a", "#9ee7fc"],
    weather: "galaxy",
    allLand: true,
    caption: "Pile sand into galaxies. Hollow basins scatter constellations.",
  },
  microscopic: {
    label: "Microscopic",
    props: ["cell", "enzyme", "nucleus"],
    colors: ["#55d3a9", "#f4ba65", "#ee88c1"],
    weather: "cytoplasm",
    allLand: true,
    caption: "Cells pulse while microbes and phages drift through the slide.",
  },
  neuron: {
    label: "Neuron network",
    props: ["neuron", "synapse", "axon"],
    colors: ["#8d79e9", "#62d6ed", "#f9b981"],
    weather: "impulses",
    allLand: true,
    caption: "Raise ridges to grow neurons; signals race along their branches.",
  },
  atomic: {
    label: "Atomic",
    props: ["atom", "orbital", "crystal"],
    colors: ["#7dc9ef", "#f1a5cb", "#fff0a2"],
    weather: "electrons",
    allLand: true,
    caption: "Orbiting electrons circle atomic nuclei across the terrain.",
  },
  cyberpunk: {
    label: "Cyberpunk",
    props: ["hologram", "antenna", "circuit"],
    colors: ["#ff6cc9", "#60f2df", "#8d83fb"],
    weather: "neon-rain",
    clouds: true,
    allLand: true,
    caption: "Raise connected city blocks: neon towers, wet streets, traffic, and crowds emerge from the sand.",
  },
  surreal: {
    label: "Dreamscape",
    props: ["eye", "arch", "mushroom", "planet"],
    colors: ["#f39fc7", "#a7a2ed", "#ffdd91"],
    weather: "dream",
    allLand: true,
    caption: "Floating eyes, impossible arches, and dreamlike pollen.",
  },
  monochrome: {
    label: "Field study",
    props: ["tree", "rock", "marker"],
    colors: ["#809293", "#c0ceca", "#506366"],
    weather: "fog",
    caption: "Sculptural trees emerge through soft drifting fog.",
  },
};
export const AQUATIC_ROSTER = [
  "shark",
  "manta",
  "mermaid",
  "mermaid",
  "mermaid",
  "merman",
  "merman",
  "koi",
];
export const WORLD_ROSTERS = {
  earth: null,
  mars: [
    "voidray",
    "dusthopper",
    "dusthopper",
    "dusthopper",
    "dusthopper",
    "dusthopper",
    "starseed",
    "starseed",
  ],
  atlantis: AQUATIC_ROSTER,
  alien: [
    "voidray",
    "glowbug",
    "glowbug",
    "glowbug",
    "glowbug",
    "glowbug",
    "starseed",
    "starseed",
  ],
  moon: [
    "voidray",
    "lunamoth",
    "lunamoth",
    "lunamoth",
    "lunamoth",
    "lunamoth",
    "drone",
    "drone",
  ],
  ice: [
    "polarbear",
    "penguin",
    "penguin",
    "penguin",
    "walrus",
    "walrus",
    "narwhal",
    "narwhal",
  ],
  volcanic: [
    "heatserpent",
    "lavafinch",
    "lavafinch",
    "lavafinch",
    "lavafinch",
    "lavafinch",
    "koi",
    "koi",
  ],
  desert: [
    "sandscorpion",
    "dusthopper",
    "dusthopper",
    "dusthopper",
    "dusthopper",
    "dusthopper",
    "dusthopper",
    "dusthopper",
  ],
  forest: [
    "wolf",
    "fox",
    "stagbeetle",
    "stagbeetle",
    "stagbeetle",
    "deer",
    "deer",
    "koi",
  ],
  coral: [
    "shark",
    "seahorse",
    "seahorse",
    "seahorse",
    "seahorse",
    "seahorse",
    "koi",
    "koi",
  ],
  tundra: [
    "brownbear",
    "dallsheep",
    "dallsheep",
    "dallsheep",
    "dallsheep",
    "moose",
    "moose",
    "muskox",
  ],
  synthwave: [
    "neonbehemoth",
    "glitchimp",
    "glitchimp",
    "glitchimp",
    "glitchimp",
    "velvetphantom",
    "velvetphantom",
    "prismwing",
  ],
  thermal: [
    "heatserpent",
    "ventcrab",
    "ventcrab",
    "ventcrab",
    "ventcrab",
    "ventcrab",
    "ventcrab",
    "ventcrab",
  ],
  topographic: [
    "wolf",
    "mountaingoat",
    "mountaingoat",
    "mountaingoat",
    "mountaingoat",
    "mountaingoat",
    "koi",
    "koi",
  ],
  infrared: [
    "heatserpent",
    "lavafinch",
    "lavafinch",
    "lavafinch",
    "lavafinch",
    "lavafinch",
    "starseed",
    "starseed",
  ],
  copper: [
    "voidray",
    "clockbeetle",
    "clockbeetle",
    "clockbeetle",
    "clockbeetle",
    "clockbeetle",
    "drone",
    "drone",
  ],
  emerald: [
    "voidray",
    "jadebird",
    "jadebird",
    "jadebird",
    "jadebird",
    "jadebird",
    "starseed",
    "starseed",
  ],
  candy: [
    "voidray",
    "sugarsnail",
    "sugarsnail",
    "sugarsnail",
    "sugarsnail",
    "sugarsnail",
    "starseed",
    "starseed",
  ],
  deepsea: [
    "anglerfish",
    "seahorse",
    "seahorse",
    "seahorse",
    "koi",
    "koi",
    "koi",
    "koi",
  ],
  universe: [
    "voidray",
    "starseed",
    "starseed",
    "starseed",
    "starseed",
    "starseed",
    "drone",
    "drone",
  ],
  microscopic: [
    "phage",
    "microbe",
    "microbe",
    "microbe",
    "microbe",
    "microbe",
    "microbe",
    "microbe",
  ],
  neuron: [
    "phage",
    "signalmoth",
    "signalmoth",
    "signalmoth",
    "signalmoth",
    "microbe",
    "microbe",
    "microbe",
  ],
  atomic: [
    "phage",
    "electronbug",
    "electronbug",
    "electronbug",
    "electronbug",
    "electronbug",
    "microbe",
    "microbe",
  ],
  cyberpunk: [
    "voidray",
    "drone",
    "drone",
    "drone",
    "drone",
    "drone",
    "prismwing",
    "prismwing",
  ],
  surreal: [
    "voidray",
    "dreamwhale",
    "dreamwhale",
    "dreamwhale",
    "dreamwhale",
    "dreamwhale",
    "starseed",
    "starseed",
  ],
  monochrome: [
    "voidray",
    "inkbird",
    "inkbird",
    "inkbird",
    "inkbird",
    "inkbird",
    "drone",
    "drone",
  ],
};
export function rosterForWorld(theme, fallback) {
  return [...(WORLD_ROSTERS[theme] || fallback)];
}

export const WORLD_SIGNATURES = Object.fromEntries(
  Object.entries(WORLD_FAUNA).map(([id, animal]) => [animal.world, id]),
);
WORLD_SIGNATURES.ice = "narwhal";
