// Scenery recipes share terrain rules; each theme has its own palette and motion.
export const LANDSCAPES = {
  earth: {
    label: "Earth",
    props: ["tree", "tree", "flowers", "rock"],
    colors: ["#4e8050", "#8caf67", "#d3a969"],
    weather: "clouds",
    waves: true,
    caption: "Wind in the trees. Waves finding the shore.",
  },
  mars: {
    label: "Mars",
    props: ["rock", "spire", "rock"],
    colors: ["#a95437", "#d88754", "#754032"],
    weather: "dust",
    caption: "Rust-red spires and wandering dust devils.",
  },
  atlantis: {
    label: "Atlantis",
    props: ["seaweed", "coral", "knoll", "ruin", "chest", "trident"],
    colors: ["#3bc1a0", "#c36ea6", "#b6ce9c"],
    weather: "bubbles",
    underwater: true,
    caption: "Sunken treasure, ancient tridents, and forests of kelp.",
  },
  alien: {
    label: "Alien world",
    props: ["mushroom", "crystal", "mushroom"],
    colors: ["#b46bc8", "#79ebbd", "#f4ba71"],
    weather: "spores",
    caption: "Breathing mushrooms and drifting luminous spores.",
  },
  moon: {
    label: "Moon",
    props: ["crater", "rock", "antenna"],
    colors: ["#98a4ad", "#d0d7d7", "#596677"],
    weather: "meteors",
    caption: "Silent craters under a passing meteor shower.",
  },
  ice: {
    label: "Glacier",
    props: ["crystal", "snowpine", "rock"],
    colors: ["#a0dceb", "#edf9ef", "#73aeca"],
    weather: "snow",
    waves: true,
    caption: "Snow flurries, glacial crystals, and frozen shores.",
  },
  volcanic: {
    label: "Volcanic",
    props: ["rock", "spire", "vent"],
    colors: ["#413c45", "#963c31", "#ff7934"],
    weather: "embers",
    eruption: true,
    caption: "Raise a tall mountain to awaken the volcano.",
  },
  desert: {
    label: "Sahara",
    props: ["palm", "cactus", "rock"],
    colors: ["#859453", "#d9b878", "#af8553"],
    weather: "sand",
    waves: true,
    caption: "Windblown dunes and palms beside the oasis.",
  },
  forest: {
    label: "Ancient forest",
    props: ["tree", "tree", "mushroom", "flowers"],
    colors: ["#28664d", "#589153", "#dcaa62"],
    weather: "rain",
    waves: true,
    caption: "Drifting rainclouds above an ancient forest.",
  },
  coral: {
    label: "Coral reef",
    props: ["coral", "seaweed", "shell", "knoll"],
    colors: ["#ee947d", "#6bcbb2", "#dac188"],
    weather: "bubbles",
    underwater: true,
    caption: "Branching coral, pearl shells, and sunlit currents.",
  },
  tundra: {
    label: "Tundra",
    props: ["snowpine", "rock", "flowers"],
    colors: ["#6d9380", "#dbe8d6", "#a7a494"],
    weather: "snow",
    waves: true,
    caption: "A quiet treeline beneath wind-driven snow.",
  },
  synthwave: {
    label: "Synthwave",
    props: ["pyramid", "crystal", "arch"],
    colors: ["#e67dca", "#75ceda", "#9975d9"],
    weather: "neon",
    caption: "Neon monuments pulse across a digital landscape.",
  },
  thermal: {
    label: "Thermal",
    props: ["vent", "crystal", "rock"],
    colors: ["#dd925e", "#e3c374", "#ab5d78"],
    weather: "steam",
    caption: "Geothermal pools release slow columns of steam.",
  },
  topographic: {
    label: "Classic topo",
    props: ["tree", "marker", "rock"],
    colors: ["#638052", "#d8c087", "#a08a66"],
    weather: "clouds",
    waves: true,
    caption: "Survey markers, pine groves, and a coastal breeze.",
  },
  infrared: {
    label: "Infrared",
    props: ["crystal", "spire", "vent"],
    colors: ["#df6475", "#ffa16b", "#85549d"],
    weather: "embers",
    caption: "Warm fissures and drifting embers reveal the land.",
  },
  copper: {
    label: "Copper",
    props: ["gear", "spire", "pipe"],
    colors: ["#ba8968", "#7bb5a5", "#e0bb82"],
    weather: "steam",
    caption: "Copper mechanisms and patina-tinted steam.",
  },
  emerald: {
    label: "Emerald city",
    props: ["tower", "crystal", "arch"],
    colors: ["#58b88d", "#b0df95", "#dfc68b"],
    weather: "fireflies",
    caption: "Jade towers glow beneath a cloud of fireflies.",
  },
  candy: {
    label: "Candy land",
    props: ["lollipop", "gumdrop", "mushroom"],
    colors: ["#e986b2", "#f3ce80", "#a3c8dc"],
    weather: "sprinkles",
    clouds: true,
    caption: "Cotton-candy clouds and falling rainbow sprinkles.",
  },
  deepsea: {
    label: "Abyss",
    props: ["vent", "jellyfish", "ruin", "coral"],
    colors: ["#3a878f", "#9a90c9", "#5cbbaa"],
    weather: "marine-snow",
    underwater: true,
    caption: "Glowing jellyfish and vents in the deep ocean.",
  },
  universe: {
    label: "Universe",
    props: ["starcore", "planet", "nebula"],
    colors: ["#7050b7", "#ffbf8a", "#9ee7fc"],
    weather: "galaxy",
    allLand: true,
    caption: "Pile sand into galaxies. Hollow basins scatter constellations.",
  },
  microscopic: {
    label: "Microscopic",
    props: ["cell", "enzyme", "nucleus"],
    colors: ["#55d3a9", "#f4ba65", "#ee88c1"],
    weather: "cytoplasm",
    allLand: true,
    caption: "Cells pulse while microbes and phages drift through the slide.",
  },
  neuron: {
    label: "Neuron network",
    props: ["neuron", "synapse", "axon"],
    colors: ["#8d79e9", "#62d6ed", "#f9b981"],
    weather: "impulses",
    allLand: true,
    caption: "Raise ridges to grow neurons; signals race along their branches.",
  },
  atomic: {
    label: "Atomic",
    props: ["atom", "orbital", "crystal"],
    colors: ["#7dc9ef", "#f1a5cb", "#fff0a2"],
    weather: "electrons",
    allLand: true,
    caption: "Orbiting electrons circle atomic nuclei across the terrain.",
  },
  cyberpunk: {
    label: "Cyberpunk",
    props: ["tower", "hologram", "circuit", "antenna"],
    colors: ["#ff6cc9", "#60f2df", "#8d83fb"],
    weather: "neon",
    allLand: true,
    caption: "Neon towers and scanning drones illuminate the grid.",
  },
  surreal: {
    label: "Dreamscape",
    props: ["eye", "arch", "mushroom", "planet"],
    colors: ["#f39fc7", "#a7a2ed", "#ffdd91"],
    weather: "dream",
    allLand: true,
    caption: "Floating eyes, impossible arches, and dreamlike pollen.",
  },
  monochrome: {
    label: "Field study",
    props: ["tree", "rock", "marker"],
    colors: ["#809293", "#c0ceca", "#506366"],
    weather: "fog",
    caption: "Sculptural trees emerge through soft drifting fog.",
  },
};
export const AQUATIC_ROSTER = [
  "shark",
  "koi",
  "koi",
  "koi",
  "koi",
  "koi",
  "koi",
  "koi",
];

export const WORLD_ROSTERS = {
  earth: null,
  atlantis: AQUATIC_ROSTER,
  coral: AQUATIC_ROSTER,
  deepsea: AQUATIC_ROSTER,
  forest: ["wolf", "deer", "deer", "deer", "rabbit", "rabbit", "koi", "koi"],
  tundra: ["wolf", "deer", "deer", "rabbit", "rabbit", "rabbit", "koi", "koi"],
  ice: ["wolf", "deer", "rabbit", "rabbit", "koi", "koi", "koi", "koi"],
  desert: ["fox", "rabbit", "rabbit", "rabbit", "deer", "deer", "koi", "koi"],
  mars: [
    "voidray",
    "starseed",
    "starseed",
    "starseed",
    "drone",
    "drone",
    "microbe",
    "microbe",
  ],
  moon: [
    "voidray",
    "starseed",
    "starseed",
    "starseed",
    "drone",
    "drone",
    "drone",
    "drone",
  ],
  alien: [
    "phage",
    "microbe",
    "microbe",
    "microbe",
    "microbe",
    "microbe",
    "voidray",
    "starseed",
  ],
  volcanic: [
    "voidray",
    "starseed",
    "starseed",
    "starseed",
    "drone",
    "drone",
    "koi",
    "koi",
  ],
  synthwave: [
    "voidray",
    "starseed",
    "starseed",
    "drone",
    "drone",
    "drone",
    "microbe",
    "microbe",
  ],
  copper: [
    "drone",
    "drone",
    "drone",
    "drone",
    "starseed",
    "starseed",
    "voidray",
    "microbe",
  ],
  emerald: [
    "drone",
    "drone",
    "starseed",
    "starseed",
    "starseed",
    "voidray",
    "microbe",
    "microbe",
  ],
  thermal: [
    "phage",
    "microbe",
    "microbe",
    "microbe",
    "drone",
    "drone",
    "starseed",
    "starseed",
  ],
  topographic: [
    "fox",
    "rabbit",
    "rabbit",
    "deer",
    "deer",
    "deer",
    "koi",
    "koi",
  ],
  infrared: [
    "voidray",
    "starseed",
    "starseed",
    "starseed",
    "drone",
    "drone",
    "microbe",
    "microbe",
  ],
  candy: [
    "phage",
    "microbe",
    "microbe",
    "microbe",
    "starseed",
    "starseed",
    "starseed",
    "drone",
  ],
  monochrome: [
    "wolf",
    "deer",
    "deer",
    "rabbit",
    "rabbit",
    "drone",
    "koi",
    "koi",
  ],
  universe: [
    "voidray",
    "starseed",
    "starseed",
    "starseed",
    "starseed",
    "starseed",
    "drone",
    "drone",
  ],
  microscopic: [
    "phage",
    "microbe",
    "microbe",
    "microbe",
    "microbe",
    "microbe",
    "microbe",
    "microbe",
  ],
  neuron: [
    "phage",
    "microbe",
    "microbe",
    "microbe",
    "microbe",
    "microbe",
    "drone",
    "drone",
  ],
  atomic: [
    "phage",
    "microbe",
    "microbe",
    "microbe",
    "starseed",
    "starseed",
    "starseed",
    "drone",
  ],
  cyberpunk: [
    "voidray",
    "drone",
    "drone",
    "drone",
    "drone",
    "drone",
    "starseed",
    "starseed",
  ],
  surreal: [
    "voidray",
    "starseed",
    "starseed",
    "starseed",
    "microbe",
    "microbe",
    "drone",
    "drone",
  ],
};
export function rosterForWorld(theme, fallback) {
  return [...(WORLD_ROSTERS[theme] || fallback)];
}
